package:
  name: elemental-kinds
  version: "0.3.0dev0"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - elemental-core
  run:
    - python
    - elemental-core

test:
  requires:
    - pytest
  imports:
    - elemental_kinds

about:
  home: https://github.com/artplusplus/elemental-kinds.
  summary: elemental-kinds is a collection of Attribute Kind classes.
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE
